//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyData
    {
        public int stationNumber { get; set; }
        public int year { get; set; }
        public int month { get; set; }
        public int day { get; set; }
        public Nullable<decimal> minTemp { get; set; }
        public Nullable<decimal> maxTemp { get; set; }
        public Nullable<decimal> rainfall { get; set; }
        public Nullable<int> rainDays { get; set; }
    
        public virtual Station Station { internal get; set; }
    }
}
